//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacitySource) DeepCopyInto(out *CapacitySource) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PerDeviceCount != nil {
		in, out := &in.PerDeviceCount, &out.PerDeviceCount
		*out = new(LabelRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacitySource.
func (in *CapacitySource) DeepCopy() *CapacitySource {
	if in == nil {
		return nil
	}
	out := new(CapacitySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemandSource) DeepCopyInto(out *DemandSource) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemandSource.
func (in *DemandSource) DeepCopy() *DemandSource {
	if in == nil {
		return nil
	}
	out := new(DemandSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelRef) DeepCopyInto(out *LabelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelRef.
func (in *LabelRef) DeepCopy() *LabelRef {
	if in == nil {
		return nil
	}
	out := new(LabelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConditionRequirement) DeepCopyInto(out *NodeConditionRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConditionRequirement.
func (in *NodeConditionRequirement) DeepCopy() *NodeConditionRequirement {
	if in == nil {
		return nil
	}
	out := new(NodeConditionRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackingProfile) DeepCopyInto(out *PackingProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackingProfile.
func (in *PackingProfile) DeepCopy() *PackingProfile {
	if in == nil {
		return nil
	}
	out := new(PackingProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackingProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackingProfileList) DeepCopyInto(out *PackingProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PackingProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackingProfileList.
func (in *PackingProfileList) DeepCopy() *PackingProfileList {
	if in == nil {
		return nil
	}
	out := new(PackingProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackingProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackingProfileSpec) DeepCopyInto(out *PackingProfileSpec) {
	*out = *in
	in.DemandSource.DeepCopyInto(&out.DemandSource)
	in.CapacitySource.DeepCopyInto(&out.CapacitySource)
	in.ReadinessSignal.DeepCopyInto(&out.ReadinessSignal)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]RuleRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackingProfileSpec.
func (in *PackingProfileSpec) DeepCopy() *PackingProfileSpec {
	if in == nil {
		return nil
	}
	out := new(PackingProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackingProfileStatus) DeepCopyInto(out *PackingProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackingProfileStatus.
func (in *PackingProfileStatus) DeepCopy() *PackingProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PackingProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadinessSignal) DeepCopyInto(out *ReadinessSignal) {
	*out = *in
	if in.NodeConditions != nil {
		in, out := &in.NodeConditions, &out.NodeConditions
		*out = make([]NodeConditionRequirement, len(*in))
		copy(*out, *in)
	}
	if in.RequiredLabels != nil {
		in, out := &in.RequiredLabels, &out.RequiredLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadinessSignal.
func (in *ReadinessSignal) DeepCopy() *ReadinessSignal {
	if in == nil {
		return nil
	}
	out := new(ReadinessSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRef) DeepCopyInto(out *RuleRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRef.
func (in *RuleRef) DeepCopy() *RuleRef {
	if in == nil {
		return nil
	}
	out := new(RuleRef)
	in.DeepCopyInto(out)
	return out
}
