{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kompakt.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompakt.labels" . | nindent 4 }}
rules:
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kompakt.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompakt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kompakt.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "kompakt.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
