apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kompakt.fullname" . }}
  labels:
    {{- include "kompakt.labels" . | nindent 4 }}
webhooks:
    - name: pod-gate-injector.kompakt.io
      admissionReviewVersions: [v1]
      clientConfig:
        service:
          name: {{ include "kompakt.fullname" . }}
          namespace: {{ .Release.Namespace }}
          path: /mutate-v1-pod
          port: 443
      failurePolicy: {{ .Values.webhook.failurePolicy }}
      sideEffects: None
      reinvocationPolicy: IfNeeded
      timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
      rules:
        - apiGroups: [""]
          apiVersions: [v1]
          operations: [CREATE]
          resources: [pods]
          scope: Namespaced
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values: [kube-system, kube-public, kube-node-lease, {{ .Release.Namespace }}]
